2018-08-05 00:57:48,739 INFO: Microblog startup [in D:\Code\flask-demo\app\__init__.py:75]
2018-08-05 00:59:27,391 INFO: Microblog startup [in D:\Code\flask-demo\app\__init__.py:75]
2018-08-05 00:59:55,529 INFO: Microblog startup [in D:\Code\flask-demo\app\__init__.py:75]
2018-08-05 01:01:47,892 INFO: Microblog startup [in D:\Code\flask-demo\app\__init__.py:75]
2018-08-05 01:01:54,585 INFO: Microblog startup [in D:\Code\flask-demo\app\__init__.py:75]
2018-08-05 01:02:20,604 ERROR: Exception on /index [GET] [in c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\Code\flask-demo\app\main\routes.py", line 46, in index
    prev_url=prev_url)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Code\flask-demo\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\Code\flask-demo\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\Code\flask-demo\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "D:\Code\flask-demo\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "D:\Code\flask-demo\app\templates\_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2018-08-05 01:10:12,504 INFO: Microblog startup [in D:\Code\flask-demo\app\__init__.py:75]
2018-08-05 01:10:19,900 ERROR: Exception on /index [GET] [in c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "D:\Code\flask-demo\app\main\routes.py", line 46, in index
    prev_url=prev_url)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\Code\flask-demo\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\Code\flask-demo\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "D:\Code\flask-demo\app\templates\base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "D:\Code\flask-demo\app\templates\index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "D:\Code\flask-demo\app\templates\_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\ayam\.virtualenvs\flask-demo-9pyhxggq\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
